#!/usr/bin/env python3
"""
Detects the frame files in assets/frames (and matching mattes in assets/mattes),
sorts them NUMERICALLY (frame-2 comes before frame-19) and writes
assets/frames/manifest.js.  Re-run whenever the frame set changes:

    python3 tools/build_manifest.py
"""
import os, re, json, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FR = os.path.join(ROOT, 'assets', 'frames')
MT = os.path.join(ROOT, 'assets', 'mattes')
exts = ('.jpg', '.jpeg', '.png', '.webp')

def nat(name):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', name)]

frames = sorted([f for f in os.listdir(FR) if f.lower().endswith(exts)], key=nat)
mattes = []
for f in frames:
    stem = os.path.splitext(f)[0]
    m = stem + '.png'
    mattes.append(m if os.path.exists(os.path.join(MT, m)) else None)
has_mattes = all(mattes)

manifest = {
    'frameDir': 'assets/frames/',
    'matteDir': 'assets/mattes/',
    'frames': frames,
    'mattes': mattes if has_mattes else [],
}
out = os.path.join(FR, 'manifest.js')
with open(out, 'w') as fh:
    fh.write('/* generated by tools/build_manifest.py — do not edit by hand */\n')
    fh.write('window.STABILIZER_FRAMES = ' + json.dumps(manifest, indent=1) + ';\n')
print(f'{len(frames)} frames, mattes: {"yes" if has_mattes else "no"} -> {out}')
